version: "3.8"
services:
   web:
      image: rachko69/bgapp-web
      ports:
         - 8080:80
      volumes:
         - "${PROJECT_ROOT}:/var/www/html:ro"
      networks:
         - app-network
      deploy:
         replicas: 5
   db:
      image: rachko69/bgapp-db
      networks:
         - app-network
      environment:
         MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
   app-network:
